version: "2"

run:
  tests: true
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - godot
    - misspell
    - whitespace

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
