run:
  tests: true
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - varcheck
    - godot
    - gofmt
    - gofumpt
    - goimports
    - misspell
    - whitespace
