name: Workflow
on: [push]
jobs:
  fmt:
    name: Run formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.24.0
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.12"
      - run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      - run: cargo fmt --all -- --check
      - run: uv sync --locked --all-extras --dev
      - run: uv run ruff format
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.24.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          working-directory: leetcode
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.12"
      - run: golangci-lint run
      - run: cargo clippy
      - run: uv sync --locked --all-extras --dev
      - run: uv run ruff check
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.24.0
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.12"
      - run: go test ./...
      - run: cargo test
      - run: uv sync --locked --all-extras --dev
      - run: uv run python leetcode/run_tests.py
